Repository mayadata-io/oep-e2e, pull requests merged in 2020-03, with the labels that each got.

#238 (bug):Changed job name for openebs-jiva-upgrade
  litmus/director/openebs-upgrade-jiva/run_litmus_test.yml
  litmus/director/openebs-upgrade-jiva/test.yml
  litmus/director/openebs-upgrade-jiva/test_vars.yml
Labels: bug-fix

#257 [iuoi14]: Install OpenEBS using custom resource limits
  litmus/director/openebs-resource-limit-installation/README.md
  litmus/director/openebs-resource-limit-installation/run_litmus_test.yml
  litmus/director/openebs-resource-limit-installation/test.yml
  litmus/director/openebs-resource-limit-installation/test_vars.yml
Labels: e2e-test-p1, install, resource-limits

#251 [iuod28]Upgrade the application with 3 replicas when one replica pod is not running
  litmus/director/upgrade-replica-pod-pending/run_litmus_test.yml
  litmus/director/upgrade-replica-pod-pending/test.yml
  litmus/director/upgrade-replica-pod-pending/test_vars.yml
Labels: e2e-dev-complete, e2e-test-p1

#252 [iuod30]:Upgrade the application with 3 replicas when all replica pod is not running
  litmus/director/upgrade-all-replica-pod-pending/run_litmus_test.yml
  litmus/director/upgrade-all-replica-pod-pending/test.yml
  litmus/director/upgrade-all-replica-pod-pending/test_vars.yml
Labels: e2e-dev-complete, e2e-test-p1

#250 (big-fix): Adding openebs cleanup task in the tests and cleaning up node labels of the cluster
  litmus/director/openebs-control-plane-test/test.yml
  litmus/director/openebs-control-plane-test/test_vars.yml
  litmus/director/openebs-data-plane-test/test.yml
  litmus/director/openebs-data-plane-test/test_vars.yml
  litmus/director/openebs-install/test.yml
  litmus/director/openebs-install/test_vars.yml
  litmus/director/openebs-self-install/test.yml
  litmus/director/openebs-self-install/test_vars.yml
  utils/openebs-cleanup.yml
  utils/openebs-label-cleanup.yaml
Labels: bug-fix

#247 [iuoi06]: Install OpenEBS on a machine already OpenEBS is installed with same version using operator.yaml
  litmus/director/openebs-reinstallation/README.md
  litmus/director/openebs-reinstallation/run_litmus_test.yml
  litmus/director/openebs-reinstallation/test.yml
  litmus/director/openebs-reinstallation/test_vars.yml
Labels: e2e-test-p1

#258 Added readme for upgrade application when replicas are not in running state
  litmus/director/upgrade-all-replica-pod-pending/README.md
  litmus/director/upgrade-replica-pod-pending/README.md
Labels: documentation

#264 Added tcid in directory structure
  litmus/director/tcid-iuod12-volume-upgrade/run_litmus_test.yml
  litmus/director/tcid-iuod12-volume-upgrade/test.yml
  litmus/director/tcid-iuod12-volume-upgrade/test_vars.yml
  litmus/director/tcid-iuod27-volume-upgrade-jiva/run_litmus_test.yml
  litmus/director/tcid-iuod27-volume-upgrade-jiva/test.yml
  litmus/director/tcid-iuod27-volume-upgrade-jiva/test_vars.yml
  litmus/director/tcid-iuod28-upgrade-replica-pod-pending/README.md
  litmus/director/tcid-iuod28-upgrade-replica-pod-pending/run_litmus_test.yml
  litmus/director/tcid-iuod28-upgrade-replica-pod-pending/test.yml
  litmus/director/tcid-iuod28-upgrade-replica-pod-pending/test_vars.yml
  litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/README.md
  litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/run_litmus_test.yml
  litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/test.yml
  litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/test_vars.yml
  litmus/director/tcid-iuoi01-openebs-self-install/run_litmus_test.yml
  litmus/director/tcid-iuoi01-openebs-self-install/test.yml
  litmus/director/tcid-iuoi01-openebs-self-install/test_vars.yml
  litmus/director/tcid-iuoi02-openebs-install/run_litmus_test.yml
  litmus/director/tcid-iuoi02-openebs-install/test.yml
  litmus/director/tcid-iuoi02-openebs-install/test_vars.yml
  litmus/director/tcid-iuoi03-openebs-control-plane/run_litmus_test.yml
  litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
  litmus/director/tcid-iuoi03-openebs-control-plane/test_vars.yml
  litmus/director/tcid-iuoi04-openebs-data-plane/run_litmus_test.yml
  litmus/director/tcid-iuoi04-openebs-data-plane/test.yml
  litmus/director/tcid-iuoi04-openebs-data-plane/test_vars.yml
  litmus/director/tcid-iuoi06-openebs-reinstallation/README.md
  litmus/director/tcid-iuoi06-openebs-reinstallation/run_litmus_test.yml
  litmus/director/tcid-iuoi06-openebs-reinstallation/test.yml
  litmus/director/tcid-iuoi06-openebs-reinstallation/test_vars.yml
  litmus/director/tcid-iuoi14-openebs-resource-limit-installation/README.md
  litmus/director/tcid-iuoi14-openebs-resource-limit-installation/run_litmus_test.yml
  litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml
  litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test_vars.yml
Labels: enhancement

#253 [iuod29]:Upgrade the application with 3 replicas when two replica pod is not running
  litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/README.md
  litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/run_litmus_test.yml
  litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/test.yml
  litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/test_vars.yml
Labels: e2e-test-p2

#269 Changed path in args of litmus job
  litmus/director/tcid-iuod08-pool-upgrade/run_litmus_test.yml
  litmus/director/tcid-iuod12-volume-upgrade/run_litmus_test.yml
  litmus/director/tcid-iuod27-volume-upgrade-jiva/run_litmus_test.yml
  litmus/director/tcid-iuod28-upgrade-replica-pod-pending/run_litmus_test.yml
  litmus/director/tcid-iuod29-upgrade-two-replica-pod-pending/run_litmus_test.yml
  litmus/director/tcid-iuod30-upgrade-all-replica-pod-pending/run_litmus_test.yml
  litmus/director/tcid-iuoi01-openebs-self-install/run_litmus_test.yml
  litmus/director/tcid-iuoi02-openebs-install/run_litmus_test.yml
  litmus/director/tcid-iuoi03-openebs-control-plane/run_litmus_test.yml
  litmus/director/tcid-iuoi04-openebs-data-plane/run_litmus_test.yml
  litmus/director/tcid-iuoi06-openebs-reinstallation/run_litmus_test.yml
  litmus/director/tcid-iuoi14-openebs-resource-limit-installation/run_litmus_test.yml
Labels: bug-fix

#261 Added readme of jobs in oep repo
  litmus/director/cassandra/README.md
  litmus/director/cluster-connect-check/README.md
  litmus/director/configs-db/README.md
  litmus/director/consul/README.md
  litmus/director/ingress-nginx/README.md
  litmus/director/maya-io-server/README.md
  litmus/director/maya-ui/README.md
  litmus/director/mysql/README.md
  litmus/director/openebs-control-plane-test/README.md
  litmus/director/openebs-data-plane-test/README.md
  litmus/director/openebs-self-install/README.md
  litmus/director/openebs-upgrade-jiva/README.md
  litmus/director/volume-upgrade/README.md
Labels: enhancement

#277 Fix: added node_id[] in the test openebs install test
  litmus/director/tcid-iuoi02-openebs-install/test.yml
Labels: bug-fix

#278 (Fix):Added node name in clean-up task
  utils/openebs-label-cleanup.yml
Labels: bug-fix

#281 [fix]Added task to check openebs components are deleted or not
  utils/openebs-cleanup.yml
Labels: bug-fix

#275 [tcid:iuod24]Upgrade the pools when one pool pod is not running
  litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/README.md
  litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/run_litmus_test.yml
  litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/test.yml
  litmus/director/tcid-iuod24-pool-upgrade-one-pod-not-running/test_vars.yml
Labels: e2e-dev-complete, e2e-test-p1, enhancement

#279 [tcid:iuod23]Upgrade the application with 3 replicas when all pool pods are running
  litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/README.md
  litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/run_litmus_test.yml
  litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/test.yml
  litmus/director/tcid-iuod23-pool-upgrade-all-pod-running/test_vars.yml
Labels: e2e-dev-complete, e2e-test-p1, enhancement

#274 Added python script to update readme.md
  utils/result_update.py
Labels: DO NOT MERGE

#305 Added new task to verify that openebs is removed from cluster.
  utils/openebs-cleanup.yml
Labels: bug-fix

#300 tcid-iuod26:Upgrade the application with 3 replicas when three(all) pool pods is not running
  litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/README.md
  litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/run_litmus_test.yml
  litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/test.yml
  litmus/director/tcid-iuod26-pool-upgrade-all-pod-not-running/test_vars.yml
Labels: e2e-dev-complete, e2e-test-p1

#316 (fix): Removed clusterComponents from task Fetching specific component details to verify
  utils/openebs-cleanup.yml
Labels: bug-fix

#314 (tcid-rec01):List capacity recommendations
  litmus/director/tcid-rec01-list-recommendations/run_litmus_test.yml
  litmus/director/tcid-rec01-list-recommendations/test.yml
  litmus/director/tcid-rec01-list-recommendations/test_vars.yml
Labels: e2e-dev-complete, e2e-test-p1

#318 Fix for openebs job in test case
  litmus/director/tcid-iuoi02-openebs-install/test.yml
Labels: bug-fix

#319 tcid-rec02:List Device recommendations
  litmus/director/tcid-rec02-device-recommendation/run_litmus_test.yml
  litmus/director/tcid-rec02-device-recommendation/test.yml
  litmus/director/tcid-rec02-device-recommendation/test_vars.yml
Labels: cstorpoolauto, e2e-dev-complete, e2e-test-p1

#326 (FIX):Changed secret name for self-connect cluster and removed openesb clean-up task
  litmus/director/tcid-iuoi01-openebs-self-install/run_litmus_test.yml
  litmus/director/tcid-iuoi01-openebs-self-install/test.yml
Labels: bug-fix

#335 Changed URL of some tasks and also changed body of openebs jobs in installation test-cases
  litmus/director/tcid-iuoi01-openebs-self-install/test.yml
  litmus/director/tcid-iuoi02-openebs-install/test.yml
  litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
  litmus/director/tcid-iuoi04-openebs-data-plane/test.yml
  litmus/director/tcid-iuoi14-openebs-resource-limit-installation/test.yml
Labels: bug-fix

#337 Added openebs namespace in job for self connected cluster
  litmus/director/tcid-iuoi01-openebs-self-install/run_litmus_test.yml
Labels: bug-fix

#339 Refactored openebs install test case and refactored clean-up tasks .
  litmus/director/tcid-iuoi01-openebs-self-install/test.yml
  litmus/director/tcid-iuoi02-openebs-install/test.yml
  utils/openebs-cleanup.yml
Labels: refactor

#343 (Bug-fix):Added separate util for application deletion
  litmus/director/tcid-iuoi02-openebs-install/test.yml
  utils/app-cleanup.yml
Labels: bug-fix, high-priority

#324 Added README.md for recommendation test cases and renamed the test cases
  litmus/director/tcid-cpre01-list-recommendations/README.md
  litmus/director/tcid-cpre01-list-recommendations/run_litmus_test.yml
  litmus/director/tcid-cpre01-list-recommendations/test.yml
  litmus/director/tcid-cpre01-list-recommendations/test_vars.yml
  litmus/director/tcid-cpre02-device-recommendation/README.md
  litmus/director/tcid-cpre02-device-recommendation/run_litmus_test.yml
  litmus/director/tcid-cpre02-device-recommendation/test.yml
  litmus/director/tcid-cpre02-device-recommendation/test_vars.yml
Labels: cstorpoolauto

#346 (Bug):Passing namespace to the openebs-cleanup.yml
  litmus/director/tcid-iuoi02-openebs-install/test.yml
Labels: bug-fix

#349 Refactored openebs-install-data-plane test case
  litmus/director/tcid-iuoi04-openebs-data-plane/test.yml
Labels: refactor

#347 Refactored openebs control plane test case
  litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
Labels: refactor

#351 Removed typo from control plane and data plane test cases
  litmus/director/tcid-iuoi03-openebs-control-plane/test.yml
  litmus/director/tcid-iuoi04-openebs-data-plane/test.yml
Labels: bug-fix
